apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-node-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: node-app
      env: dev
  template:
    metadata:
      name: node-pod
      labels:
        name: node-app
        env: dev
    spec:
      containers:
      - image: asia-south1-docker.pkg.dev/searce-cloud-consultants/first-repository/app-image:5b55d0efb353c78a3cd7c3b2080ed1aa19fd0075
        name: node-container
        ports:
        - containerPort: 8080
