apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-node-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: node-app
      env: dev
  template:
    metadata:
      name: node-pod
      labels:
        name: node-app
        env: dev
    spec:
      containers:
      - image: asia-south1-docker.pkg.dev/searce-cloud-consultants/first-repository/app-image:fee5d3bbc09443dbd8755ba47238901474de549e
        name: node-container
        ports:
        - containerPort: 8080
